export const GAME_CONFIG = {
  initialLives: 3,
  initialWave: 1,
  baseSpeed: 0.2,
  speedIncrement: 0.25,
  highWaveSpeedBonus: 0.1,
  highWaveThreshold: 5,
  speedVariationMin: 0.85,
  speedVariationMax: 1.15,
  baseEnemiesPerWave: 6,
  enemiesPerWaveIncrement: 2,
  maxEnemiesPerWave: 20,
  baseMaxOnScreen: 1,
  maxOnScreenCap: 10,
  spawnIntervalBase: 2000,
  spawnIntervalDecrement: 150,
  spawnIntervalMin: 500,
  moveIntervalMs: 25,
  waveTransitionDelayMs: 2000,
  pointsPerChar: 10,
} as const;
